// <auto-generated />
using Core.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core.Entity.Migrations
{
    [DbContext(typeof(CoreContext))]
    partial class CoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Entity.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "0e4ba25e-ee5f-4b7e-8dc6-9bac46589b9e",
                            Title = "本教程由Siegrain提供"
                        },
                        new
                        {
                            Id = 2,
                            Content = "94083904-632f-4fda-8d6e-190990088f82",
                            Title = "感谢贡献~~"
                        },
                        new
                        {
                            Id = 3,
                            Content = "81869890-7f33-4523-9806-dd80f5790db0",
                            Title = "博客地址为http://dralee.com"
                        },
                        new
                        {
                            Id = 4,
                            Content = "1e10055f-0093-448d-8ffc-cfbc571dc7c7",
                            Title = "教程内容就是docker的windows下简单使用"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
